{
    "openapi": "3.0.0",
    "info": {
        "title": "ParkimaPro API",
        "version": "0.1"
    },
    "servers": [
        {
            "url": "http://demo.pro.bmoov.co",
            "description": "API server"
        }
    ],
    "paths": {
        "/api/check/password": {
            "post": {
                "tags": [
                    "Login"
                ],
                "summary": "Check Password",
                "operationId": "cc99f564b4917736404a00a5b7aced20",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "password"
                                ],
                                "properties": {
                                    "password": {
                                        "type": "integer"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Issue the token and return the current user info",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "status": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/phone-auth/verification": {
            "put": {
                "tags": [
                    "Login"
                ],
                "summary": "Verify phone number",
                "operationId": "60bc2b831a3d601c9a0391b166ff26fe",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "phone"
                                ],
                                "properties": {
                                    "phone": {
                                        "type": "integer"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Issue the token and return the current user info",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "status": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/phone-auth/verify": {
            "put": {
                "tags": [
                    "Login"
                ],
                "summary": "Verify otp",
                "operationId": "0fd3649575095bddb729daa8071c2d65",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "phone",
                                    "otp"
                                ],
                                "properties": {
                                    "phone": {
                                        "type": "integer"
                                    },
                                    "otp": {
                                        "type": "integer"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Issue the token and return the current user info",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "status": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/get/counting": {
            "get": {
                "tags": [
                    "Parking Availability"
                ],
                "summary": "get parking spots availability",
                "operationId": "getCounting",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "parking_id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "get parking spots availability",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/edit/counting": {
            "post": {
                "tags": [
                    "Parking Availability"
                ],
                "summary": "post Payment",
                "operationId": "editParkingAvailability",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "parking_id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "free_spots",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "total_spots",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "make post payment",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/get/products": {
            "get": {
                "tags": [
                    "Enforcement"
                ],
                "summary": "get enforcement products",
                "operationId": "getEnforcementProducts",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "get enforcement products",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/make/enforcement": {
            "post": {
                "tags": [
                    "Enforcement"
                ],
                "summary": "make Enforcement",
                "operationId": "makeEnforcement",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "parking_id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "agent_name",
                        "in": "query",
                        "required": false,
                        "schema": {
                            "type": "string",
                            "default": "---"
                        }
                    },
                    {
                        "name": "type",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "***"
                        }
                    },
                    {
                        "name": "gravity",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "***"
                        }
                    },
                    {
                        "name": "cause",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "***"
                        }
                    },
                    {
                        "name": "amount",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "default": 0
                        }
                    },
                    {
                        "name": "license_plate",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "phone_number",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "enforced_car_picture",
                        "in": "query",
                        "required": false,
                        "schema": {
                            "type": "integer",
                            "default": "----"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "make enforcement",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/check/enforcement": {
            "get": {
                "tags": [
                    "Enforcement"
                ],
                "summary": "check whether a given plate carries a penalty",
                "operationId": "checkEnforcement",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "enforced_license_plate",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "check whether a given plate carries a penalty",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/cashPay/enforcement": {
            "post": {
                "tags": [
                    "Enforcement"
                ],
                "summary": "cash pay enforcement",
                "operationId": "payEnforcement",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "parking_id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "enforced_license_plate",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "enforcement_reference",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "make enforcement",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/get/plate/list": {
            "get": {
                "tags": [
                    "License Plate"
                ],
                "summary": " Get License Plate list",
                "operationId": "License Plate list",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "parking_id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "License Plate list",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/get/plate": {
            "get": {
                "tags": [
                    "License Plate"
                ],
                "summary": " Get Car session status",
                "operationId": "car session status",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "parking_id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "license_plate",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "session status",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/payment/options": {
            "get": {
                "tags": [
                    "Payment"
                ],
                "summary": " Get Payment Options",
                "operationId": "paymentOption",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get Payment Options",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/payment": {
            "post": {
                "tags": [
                    "Payment"
                ],
                "summary": "post Payment",
                "operationId": "makePostPayment",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "parking_id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "license_plate",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "barcode",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "ticket_id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "provider",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "default": "cash_payment"
                        }
                    },
                    {
                        "name": "ticket_value",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "make post payment",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/prepayment": {
            "post": {
                "tags": [
                    "Payment"
                ],
                "summary": "post Payment",
                "operationId": "makePrePayment",
                "requestBody": {
                    "description": "Station to create",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "parking_id",
                                    "plate_info",
                                    "license_plate",
                                    "ticket_duration",
                                    "phone_number"
                                ],
                                "properties": {
                                    "parking_id": {
                                        "type": "integer"
                                    },
                                    "plate_info": {
                                        "type": "array",
                                        "items": {
                                            "properties": {
                                                "type": {
                                                    "type": "string",
                                                    "example": "tn"
                                                },
                                                "background": {
                                                    "type": "string",
                                                    "example": "background"
                                                },
                                                "inputPartOne": {
                                                    "type": "string",
                                                    "example": "---"
                                                },
                                                "inputPartTwo": {
                                                    "type": "string",
                                                    "example": "----"
                                                }
                                            },
                                            "type": "object"
                                        },
                                        "default": [
                                            {
                                                "type": "tn",
                                                "background": "background",
                                                "inputPartOne": "---",
                                                "inputPartTwo": "----"
                                            }
                                        ]
                                    },
                                    "license_plate": {
                                        "type": "string"
                                    },
                                    "ticket_duration": {
                                        "type": "integer"
                                    },
                                    "phone_number": {
                                        "type": "integer"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "make pre payment",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/extension": {
            "post": {
                "tags": [
                    "Payment"
                ],
                "summary": "extension Payment",
                "operationId": "makeExtension",
                "requestBody": {
                    "description": "Station to create",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "parking_id",
                                    "plate_info",
                                    "license_plate",
                                    "ticket_duration",
                                    "phone_number"
                                ],
                                "properties": {
                                    "parking_id": {
                                        "type": "integer"
                                    },
                                    "plate_info": {
                                        "type": "array",
                                        "items": {
                                            "properties": {
                                                "type": {
                                                    "type": "string",
                                                    "example": "tn"
                                                },
                                                "background": {
                                                    "type": "string",
                                                    "example": "background"
                                                },
                                                "inputPartOne": {
                                                    "type": "string",
                                                    "example": "---"
                                                },
                                                "inputPartTwo": {
                                                    "type": "string",
                                                    "example": "----"
                                                }
                                            },
                                            "type": "object"
                                        },
                                        "default": [
                                            {
                                                "type": "tn",
                                                "background": "background",
                                                "inputPartOne": "---",
                                                "inputPartTwo": "----"
                                            }
                                        ]
                                    },
                                    "license_plate": {
                                        "type": "string"
                                    },
                                    "ticket_duration": {
                                        "type": "integer"
                                    },
                                    "phone_number": {
                                        "type": "integer"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "make extension payment",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/check/shift": {
            "post": {
                "tags": [
                    "Shift Configuration"
                ],
                "summary": "check Shift",
                "operationId": "checkShift",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "parking_id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "check Shift",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/open/shift": {
            "post": {
                "tags": [
                    "Shift Configuration"
                ],
                "summary": "Open Shift",
                "operationId": "openShift",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "parking_id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "starting_amount",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "check Shift",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/close/shift": {
            "post": {
                "tags": [
                    "Shift Configuration"
                ],
                "summary": "Close old Shift and open new one",
                "operationId": "closeShift",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "parking_id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "starting_amount",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "check Shift",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                },
                                "example": {
                                    "shift_id": "integer",
                                    "strat_shift_date": "datetime",
                                    "end_shift_date": "datetime",
                                    "total_revenue": "integer",
                                    "revenue_details": "string",
                                    "starting_amount": "integer",
                                    "total_amount": "integer"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/entryTicket/create": {
            "get": {
                "tags": [
                    "Ticket Classification"
                ],
                "summary": "Create Postpayment Ticket",
                "operationId": "createTicket",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "parking_id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Create entry ticket",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                },
                                "example": {
                                    "parking_id": 0,
                                    "ticket_id": "string",
                                    "entry_datetime": "string",
                                    "barcode_data": "string",
                                    "qrcode_data": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/ticket/consult": {
            "get": {
                "tags": [
                    "Ticket Classification"
                ],
                "summary": "Create Postpayment Ticket",
                "operationId": "consultTicket",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "parking_id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "barcode",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Create entry ticket",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                },
                                "example": {
                                    "parking_id": 0,
                                    "ticket_id": "string",
                                    "license_plate": "string",
                                    "ticket_entry_time": "string",
                                    "ticket_tariff_time": "string",
                                    "ticket_duration": "string",
                                    "original_amount": 0,
                                    "discount_amount": 0,
                                    "ticket_amount": 0
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        }
    },
    "components": {
        "parameters": {
            "Accept": {
                "name": "Accept",
                "in": "header",
                "description": "The media type accepted by the client",
                "required": true,
                "schema": {
                    "type": "string",
                    "default": "application/json"
                }
            }
        },
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "description": "Authentication Bearer Token",
                "name": "Authorization",
                "in": "header",
                "bearerFormat": "JWT",
                "scheme": "bearer"
            }
        }
    }
}